version: '3.8'

services:
  
  redis:
    image: redis:alpine
    container_name: fileprocessing_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  fileprocessing-pm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fileprocessing_pm_restapi
    environment:
      - SPRING_DATA_REDIS_HOST=fileprocessing_redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
  prometheus:
    image: prom/prometheus
    container_name: prometheus_process
    volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - fileprocessing-pm

  grafana:
    image: grafana/grafana
    container_name: grafana_process
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  redis_data:
